## 1, 2차원 Tensor 선언하기

In [ ]:
import numpy as np

# 1D with Numpy
t1 = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)
print('Rank of t1: ', t1.ndim)
print('Shape of t1: ', t1.shape)
print('t1[2:5] t1[4:-1]  = ', t1[2:5], t1[4:-1]) # [시작 번호 : 끝 번호]로 범위 지정을 통해 가져온다.
print('t1[:2] t1[3:]     = ', t1[:2], t1[3:]) # 시작 번호를 생략한 경우와 끝 번호를 생략한 경우




[0. 1. 2. 3. 4. 5. 6.]
Rank of t1:  1
Shape of t1:  (7,)
t1[2:5] t1[4:-1]  =  [2. 3. 4.] [4. 5.]
t1[:2] t1[3:]     =  [0. 1.] [3. 4. 5. 6.]


In [ ]:
# 2D with Numpy
t2 = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t2)
print('Rank  of t2: ', t2.ndim)
print('Shape of t2: ', t2.shape)


[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank  of t2:  2
Shape of t2:  (4, 3)


In [ ]:
# 1D with Torch
import torch

t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱


tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [ ]:
# 2D with Torch
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
print(t[:, 1].size()) # ↑ 위의 경우의 크기
print(t[:, :-1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.


tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## 브로드캐스팅(Broadcasting)

In [ ]:
# Vector + Scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) # -> [[1, 2], [1, 2]]
m2 = torch.FloatTensor([[3], [4]]) # -> [[3, 3], [4, 4]]
print(m1 + m2) # -> 2 x 2 Vector


tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


## 행렬 곱셈과 곱셈의 차이(Matrix Multiplication vs Multiplication)

In [ ]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [ ]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2)
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## 평균(Mean)

In [ ]:
t = torch.FloatTensor([1, 2])
print(t.mean())


tensor(1.5000)


In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())
print(t.mean(dim=0)) # 첫 번째 차원('행')을 제거
print(t.mean(dim=1)) # 두 번째 차원('열')을 제거
print(t.mean(dim=-1)) # 마지막 차원 제거


tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## 덧셈

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])

print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거


tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## 최대(Max)와 아그맥스(ArgMax)
- 아그맥스(ArgMax) : 최대 값으로 선정된 value의 index tensor

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.max()) # Returns one value: max
print(t.max(dim=0)) # Returns two values: max and argmax
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

print(t.max(dim=1))
print(t.max(dim=-1))


tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
