# view(), squeeze(), unsqueeze()는 텐서의 원소 수를 그대로 유지하면서 모양과 차원을 조절합니다.


## 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경

In [4]:
import numpy as np
import torch

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


### 3차원 텐서에서 2차원 텐서로 변경

In [5]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)


tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


### 3차원 텐서의 크기 변경

In [8]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## 스퀴즈(Squeeze) - 1인 차원을 제거한다.

In [9]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

print(ft.squeeze())
print(ft.squeeze().shape)


tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


## 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가한다.

In [14]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

# 이를 view를 써서 구현
print(ft.view([1, -1]))
print(ft.view([1, -1]).shape)
print()

print(ft.unsqueeze(1))  # 인덱스가 1부터 시작하므로 1은 두번째 차원을 의미한다.
print(ft.unsqueeze(1).shape)
print()

print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)


torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## 타입 캐스팅(Type Casting)

In [18]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())
print()

bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())
print(bt.float())


tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## 연결하기(Concatenate)
- 딥 러닝에서는 주로 모델의 입력 또는 중간 연산에서 두 개의 텐서를 연결하는 경우가 많습니다. 두 텐서를 연결해서 입력으로 사용하는 것은 두 가지의 정보를 모두 사용한다는 의미를 가지고 있습니다.

In [20]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))


tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## 스택킹(Stacking)

In [24]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

# 아래 두 코드는 동치
print(torch.stack([x, y, z])) # 3 x 2 : 첫 번째 차원이 증가
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

# dim = 1 일 때
print(torch.stack([x, y, z], dim=1)) # 2 x 3 : 두 번째 차원이 증가

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


## ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서


In [25]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])

print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place Operation(덮어쓰기 연산)
- 연산 뒤에 _를 붙이면 기존의 값을 덮어쓰기 합니다.

In [27]:
x = torch.FloatTensor([[1, 2], [3, 4]])

print(x)
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
